import type {
  BatchRecord,
  ProductFacts,
  ProductImage,
  ProductRecord,
  StoreSettings,
} from "./types";

const facts = (overrides: Partial<ProductFacts> = {}): ProductFacts => ({
  categoryId: "100003852",
  categoryLabel: "Art Supplies > Painting Supplies > Paint Brushes",
  brand: "Giorgione",
  model: "",
  material: "Nylon Hair",
  price: "",
  moq: "50",
  stock: "",
  productLength: "20",
  productWidth: "2",
  productHeight: "1",
  netWeight: "0.08",
  packageLength: "24",
  packageWidth: "11",
  packageHeight: "3",
  grossWeight: "",
  unitsPerCarton: "100",
  leadTime: "15",
  origin: "China",
  hsCode: "9603301090",
  certifications: [],
  ...overrides,
});

export const defaultSettings: StoreSettings = {
  currency: "",
  priceUnit: "",
  productGroupId: "",
  productGroupLabel: "",
  photoBankGroupId: "",
  photoBankGroupLabel: "",
  warehouseId: "",
  warehouseLabel: "",
  shippingTemplateId: "",
  shippingTemplateLabel: "",
  inventoryCode: "",
  companyProfile: "",
  afterSalesPolicy: "",
  customizationPolicy: "",
  detailTemplate: "",
  brand: "",
  origin: "",
  port: "",
  reuseCompanyProfile: false,
  reuseAfterSales: false,
  reuseCustomization: false,
  reuseDetailTemplate: false,
  reuseOrigin: false,
};

const demoImage = (id: string, url: string): ProductImage => ({
  id,
  url,
  name: url.split("/").at(-1) ?? "product image",
});

export const getMainProductImage = (product: ProductRecord): ProductImage =>
  product.images.find((image) => image.id === product.mainImageId) ?? product.images[0];

export const sampleProducts: ProductRecord[] = [
  {
    id: "product-fan-01",
    reference: "PT-FB-001",
    images: [demoImage("fan-main", "/products/fan-brush-set.webp")],
    mainImageId: "fan-main",
    title: "Professional Fan Brush Set 9 Pcs for Acrylic and Oil Painting",
    keywords: ["fan brush set", "artist paint brushes", "nylon hair brush"],
    sellingPoints: [
      "Nine graduated fan brush sizes",
      "Flexible nylon hair for controlled texture",
      "Balanced black lacquered handles",
    ],
    description:
      "A nine-piece fan brush set designed for blending, foliage, texture and soft edge work.",
    visibleTraits: ["9 pieces", "black handles", "fan-shaped bristles"],
    aiConfirmed: true,
    stage: "facts_needed",
    facts: facts({
      model: "FB-9N",
      price: "6.50",
      stock: "520",
      grossWeight: "",
    }),
    errors: ["请填写包装毛重"],
    isDemo: true,
  },
  {
    id: "product-flat-02",
    reference: "PT-FB-002",
    images: [demoImage("flat-main", "/products/flat-brush-set.webp")],
    mainImageId: "flat-main",
    title: "Flat Paint Brush Set 6 Pcs with Golden Ferrules for Artists",
    keywords: ["flat paint brushes", "artist brush set", "gold ferrule brush"],
    sellingPoints: [
      "Six useful graduated widths",
      "Smooth synthetic bristles",
      "Easy-clean matte handles",
    ],
    description: "A compact six-piece flat brush set for broad strokes, blocking and clean edges.",
    visibleTraits: ["6 pieces", "gold ferrules", "flat bristles"],
    aiConfirmed: false,
    stage: "ai_ready",
    facts: facts({
      model: "FLAT-6G",
      price: "4.80",
      stock: "860",
      grossWeight: "8.40",
    }),
    errors: ["AI 内容尚未确认"],
    isDemo: true,
  },
  {
    id: "product-round-03",
    reference: "PT-RB-001",
    images: [demoImage("round-main", "/products/round-brush-set.webp")],
    mainImageId: "round-main",
    title: "Round Detail Paint Brush Set 12 Pcs Fine Tip Artist Brushes",
    keywords: ["detail paint brush", "round brush set", "fine tip brushes"],
    sellingPoints: ["Twelve precision sizes", "Fine pointed tips", "Comfortable espresso handles"],
    description:
      "A twelve-piece detail set for miniature painting, line work and controlled highlights.",
    visibleTraits: ["12 pieces", "fine tips", "brown handles"],
    aiConfirmed: true,
    stage: "ready",
    facts: facts({
      model: "ROUND-12S",
      price: "7.20",
      stock: "1200",
      grossWeight: "9.60",
    }),
    errors: [],
    isDemo: true,
  },
  {
    id: "product-filbert-04",
    reference: "PT-FILB-001",
    images: [demoImage("filbert-main", "/products/filbert-brush-set.webp")],
    mainImageId: "filbert-main",
    title: "Filbert Artist Brush Set 7 Pcs for Acrylic and Oil Painting",
    keywords: ["filbert brush set", "acrylic paint brush", "oil painting brush"],
    sellingPoints: [
      "Seven oval filbert shapes",
      "Soft synthetic blend",
      "Deep green lacquered handles",
    ],
    description:
      "A versatile filbert brush set that combines the control of a flat brush with soft rounded edges.",
    visibleTraits: ["7 pieces", "oval tips", "green handles"],
    aiConfirmed: true,
    stage: "ready",
    facts: facts({
      model: "FILB-7G",
      price: "5.40",
      stock: "610",
      grossWeight: "8.90",
    }),
    errors: [],
    isDemo: true,
  },
];

export const sampleBatches: BatchRecord[] = [
  {
    id: "B250521-001",
    name: "扇形画笔系列",
    createdAt: "2025-05-21 10:24",
    updatedAt: "今天 15:42",
    productCount: 8,
    completion: 92,
    draftCount: 8,
    publishedCount: 0,
    reviewStatus: "none",
    reviewLabel: "等待发布",
    status: "ready",
    images: [
      "/products/fan-brush-set.webp",
      "/products/flat-brush-set.webp",
      "/products/round-brush-set.webp",
    ],
  },
  {
    id: "B250520-002",
    name: "亚麻画布 · 夏季补货",
    createdAt: "2025-05-20 16:18",
    updatedAt: "今天 09:31",
    productCount: 12,
    completion: 78,
    draftCount: 12,
    publishedCount: 0,
    reviewStatus: "none",
    reviewLabel: "等待发布",
    status: "processing",
    images: [
      "/products/flat-brush-set.webp",
      "/products/round-brush-set.webp",
      "/products/filbert-brush-set.webp",
    ],
  },
  {
    id: "B250519-003",
    name: "丙烯颜料 24 色",
    createdAt: "2025-05-19 11:07",
    updatedAt: "昨天 14:05",
    productCount: 24,
    completion: 64,
    draftCount: 24,
    publishedCount: 21,
    reviewStatus: "failed",
    reviewLabel: "3 项审核失败",
    status: "failed",
    images: [
      "/products/round-brush-set.webp",
      "/products/filbert-brush-set.webp",
      "/products/fan-brush-set.webp",
    ],
  },
  {
    id: "B250518-004",
    name: "木制画架",
    createdAt: "2025-05-18 09:56",
    updatedAt: "05-19 17:22",
    productCount: 6,
    completion: 88,
    draftCount: 6,
    publishedCount: 6,
    reviewStatus: "passed",
    reviewLabel: "已通过",
    status: "complete",
    images: [
      "/products/filbert-brush-set.webp",
      "/products/fan-brush-set.webp",
      "/products/flat-brush-set.webp",
    ],
  },
  {
    id: "B250517-005",
    name: "水彩纸本系列",
    createdAt: "2025-05-17 15:30",
    updatedAt: "05-18 10:44",
    productCount: 10,
    completion: 100,
    draftCount: 10,
    publishedCount: 10,
    reviewStatus: "passed",
    reviewLabel: "已通过",
    status: "complete",
    images: [
      "/products/flat-brush-set.webp",
      "/products/fan-brush-set.webp",
      "/products/round-brush-set.webp",
    ],
  },
  {
    id: "B250516-006",
    name: "调色盘与颜料刀",
    createdAt: "2025-05-16 13:21",
    updatedAt: "05-16 16:08",
    productCount: 12,
    completion: 55,
    draftCount: 7,
    publishedCount: 0,
    reviewStatus: "pending",
    reviewLabel: "资料处理中",
    status: "processing",
    images: [
      "/products/round-brush-set.webp",
      "/products/fan-brush-set.webp",
      "/products/filbert-brush-set.webp",
    ],
  },
];

export const createEmptyFacts = (settings: StoreSettings): ProductFacts =>
  facts({
    brand: settings.brand,
    origin: settings.origin,
    categoryId: "",
    categoryLabel: "",
    material: "",
    productLength: "",
    productWidth: "",
    productHeight: "",
    netWeight: "",
    packageLength: "",
    packageWidth: "",
    packageHeight: "",
    unitsPerCarton: "",
    leadTime: "",
    hsCode: "",
  });
